export enum ROOT_ROUTES {
  AUTH_NAVIGATION = 'AUTH_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
}

export enum AUTH_NAVIGATION {
  LOGIN_SCREEN = '[AUTH] LOGIN_SCREEN',
}

export enum APP_NAVIGATION {
  HOME = '[APP] HOME',
  BROWSE = '[APP] BROWSE',
  SELL = '[APP] SELL',
  SHOP = '[APP] SHOP',
  PROFILE = '[APP] PROFILE',
}

export enum HOME_NAVIGATION {
  HOME = '[HOME] HOME',
}
